### ISSUE TITLE
Cannot read property 'sendPayload' of null

### ISSUE THREAD

**Issue by rohitsethii** [Aniket-Engg/sol-verifier#2]
**command** :
`sol-verifier -k <etherscan API key> -c ./ballot.sol -a 0x1d1a5e345d14aa73a14bf55bb965912032209ff7 -n ropsten -p [4]`

**Expected** : should return the success status with GUID receipt.

**Actual** : throws error related to web3 provider 

> /usr/local/lib/node_modules/sol-verifier/node_modules/web3-providers/dist/web3-providers.cjs.js:49
>       if (provider.sendPayload && provider.subscribe) {
>                    ^
> 
> TypeError: Cannot read property 'sendPayload' of null
>     at ProviderResolver.resolve (/usr/local/lib/node_modules/sol-verifier/node_modules/web3-providers/dist/web3-providers.cjs.js:49:20)
>     at Web3.AbstractWeb3Module (/usr/local/lib/node_modules/sol-verifier/node_modules/web3-core/dist/web3-core.cjs.js:24:51)
>     at new Web3 (/usr/local/lib/node_modules/sol-verifier/node_modules/web3/dist/web3.cjs.js:30:68)
>     at Object.<anonymous> (/usr/local/lib/node_modules/sol-verifier/lib/verify.js:6:19)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/sol-verifier/bin/sol-verifier.js:5:20)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:188:16)
>     at bootstrap_node.js:609:3

:computer: **Environment**
     npm version - 3.5.2
     node version - 8.10.0

**Comment by Aniket-Engg** [comment]
Thanks for raising this @rohitsethii .
I can reproduce it at my end. Actually web3 is under development and this seems a version issue. I will restrict the web3 version to `web3@1.0.0-beta.37`. With that it works fine for now.

**Comment by Aniket-Engg** [comment]
closed by #3
