### ISSUE TITLE
Unable to verify with sol-verify release v1.2.0

### ISSUE THREAD

**Issue by DigvijaySS** [Aniket-Engg/sol-verifier#28]
**Current sol-verify version:** v1.2.0
**Current solidity version:** ^0.4.18;

**Payload:**
```
{ 
    key: 'XXXXXXXXXXXXXXXXXXXXXX',
    path: '/private/var/www/html/blockchain/konkrete_node/ERC20-Mintable-Contract/erc20_mintable_contract.sol',
    contractAddress: '0xBa69648023f5ca52f93bD9d1E48854c1E82ebe8b',
    network: 'ropsten',
    contractName: 'konkrete6',
    cvalues: [ 'TSTM', 'Happy Project TSTM/projects/2/interest', 12345600 ],
    optimizationFlag: false 
}
```

**Output:**
```
{ 
    status: '0',
    message: 'NOTOK',
    result: 'Fail - Unable to verify' 
}
```

I am using contract named constructor instead of keyword.

**Comment by Aniket-Engg** [comment]
Thanks @DigvijaySS  for raising this. Can you please let us know how you have deployed the contract, i mean using remix or other ways?

**Comment by DigvijaySS** [comment]
I am deploying this using ether.js deploy function.

**Comment by Aniket-Engg** [comment]
Have you tried any other way of deployment? Also please double check your constructor parameters.

**Comment by Aniket-Engg** [comment]
@DigvijaySS We have tried all the ways to reproduce it. I have deployed contract using ethers.js and successfully verified it using this package passing constructor parameters(string type too).
Still if you would like to share the related code or other information where you think something may be wrong, we will be happy to help you.

**Comment by DigvijaySS** [comment]
Looks like something wrong around the datatype.

I was deploying contract with ether.js code -
```
var tokensToDeploy = math.multiply(numOfTokens, math.pow(10, contractDecimals));
let contract = await factory.deploy(tokenSymbol, projectName, tokensToDeploy);
```

This failed! To make it work, I had to change the `tokensToDeploy` to something as below -
`var tokensToDeploy = parseInt(math.multiply(numOfTokens, math.pow(10, contractDecimals)));`

Now this works while verification.

Thanks!

**Comment by Aniket-Engg** [comment]
This seems bignumber issue. You should use some bignumber library like https://www.npmjs.com/package/big-number
