### ISSUE TITLE
Does not support array parameters

### ISSUE THREAD

**Issue by ukstv** [Aniket-Engg/sol-verifier#38]
The package, unfortunately, does not support `bytes32[]` parameter, and based on source code it does not support any array parameters.

**Comment by Aniket-Engg** [comment]
@ukstv  Thanks for raising this. Can you please add the steps to reproduce?

**Comment by Aniket-Engg** [comment]
I got your point and successfully reproduced it. To confirm, here you are talking about to pass the array as one of the constructor values as right now It accepts all parameters in an array itself. Please add if I am missing anything.

**Comment by ukstv** [comment]
> to pass the array as one of the constructor values

Exactly. Was trying to pass `bytes32[]`, and it failed.

Thank you for the package!

**Comment by Aniket-Engg** [comment]
will release it today, and you use the array in constructor then.

Thanks again for raising this.
