### ISSUE TITLE
Parser doesn't accept interfaces in function parameters

### ISSUE THREAD

**Issue by TimDaub** [Aniket-Engg/sol-verifier#5]
Hi,

see this issue for details: https://github.com/federicobond/solidity-parser-antlr/issues/55

I'm looking to upgrade this library with a parser that supports that.

**Comment by Aniket-Engg** [comment]
Thanks for raising this @TimDaub . I think in related issue you have been suggested some solutions. Although we are not using this parse in this library. Can you please add more updates about the changes you want to introduce in it and how it will be helpful to resolve the above issue (are you looking to verify the contract mentioned in the issue using this library?)

**Comment by Aniket-Engg** [comment]
> I'd be happy to add the functionality to solparse though if you preferred that.

That would be awesome.

**Comment by TimDaub** [comment]
Hi @Aniket-Engg, it's been a while.

I actually tried what I outlined in my last comment but eventually I realized that also https://github.com/federicobond/solidity-type-resolver doesn't resolve interface types reliably.

In my fork of sol-verifier, I hence just added an option to allow passing interface parameters manually: https://github.com/TimDaub/sol-verifier/commit/38100220581c8d021a4a86ada45273eb3c182fed so that I can use it in etherscan-uploader.

Back then, sol-verifier also didn't have a flattener built in, which was another reason that prompted me to create https://github.com/0xdefaceme/etherscan-uploader.
You've updated the repo frequently though and added the flattener. That kinda makes etherscan-uploader obsolete.

My proposal would hence be:

- We merge a cleaned up version of https://github.com/TimDaub/sol-verifier/commit/38100220581c8d021a4a86ada45273eb3c182fed
- I deprecate etherscan-uploader and I link to this repo

Thoughts?

**Comment by Aniket-Engg** [comment]
Hi @TimDaub, good to have you back in conversation.
  
I also agree to add as more as possible functionalities in this package. But on the other hand, I want to keep it handy and user-friendly. Adding params manually can be our last solution. For now we should try to thing about some middle way which can introduce the functionality without hampering user's ease of use.

**Comment by Aniket-Engg** [comment]
@TimDaub I am investigating it to get it worked. Can you please let me know what was the problem you faced with  https://github.com/federicobond/solidity-type-resolver

**Comment by TimDaub** [comment]
> Also i think to get the encoding right, it should return `address` for `Negotiator _negotiator`. Am I right?

It's been a really long time since I did that, so I can't remember exactly. But yes the problem had to do with an interface like "Negotiator" needing to be converted to `address` for the verification to work. If I remember correctly, solidity-type-resolver resolved an interface correctly but didn't convert it to an address and I think it was difficult for me to make a programatic decision on whether sol-verifier should e.g. always convert Interfaces to type `address`.

Hope that helps!

**Comment by Aniket-Engg** [comment]
@federicobond May be your valuable comments can suggest a better way out.

**Comment by federicobond** [comment]
I'm not exactly sure what you are looking for, but I don't think it would be hard to adapt the resolver code to convert interface types to addresses.

**Comment by Aniket-Engg** [comment]
> I think it was difficult for me to make a programatic decision on whether sol-verifier should e.g. always convert Interfaces to type address.
@federicobond We want to confirm, should interface always convert to type `address` ?

**Comment by federicobond** [comment]
AFAIK all contract and interface types should be converted to either `address` or `address payable` depending on whether they have defined a payable fallback function.

**Comment by Aniket-Engg** [comment]
Thanks @federicobond . I got it.

**Comment by Aniket-Engg** [comment]
Hi @TimDaub  I have made the required changes and release a new version. Hope this one can cover your usecase nicely. Please check it and let me know your feedback. Thanks!

**Comment by Aniket-Engg** [comment]
I have added a test case regarding this here: https://github.com/Aniket-Engg/sol-verifier/blob/master/test/sol-verifier.js#L308
which i think covers your case. 
I am closing this. Reopen if issue persists.
