### ISSUE TITLE
Track solidity releases dynamically

### ISSUE THREAD

**Issue by Aniket-Engg** [Aniket-Engg/sol-verifier#6]
should track the new Solidity releases dynamically if it is not in our list.

**Comment by Aniket-Engg** [comment]
@rohitsethii I have to revert your PR because some tests are failing. See the travis logs: https://travis-ci.com/Aniket-Engg/sol-verifier/jobs/188813509
Also please check the reliability of github APIs.

**Comment by rohitsethii** [comment]
As per the travis logs : 
`Trying to verify already verified contract (should fail)`

solc version mismatch in .sol file and package.json leads this test to fail.
there is no issue with the verification of the contract.
this is related to compiling with different solc version and deploying the contract.

**Comment by Aniket-Engg** [comment]
use https://github.com/ethereum/solc-js#using-a-legacy-version to get the solc object as per the compiler and https://solc-bin.ethereum.org/bin/list.json for getting new releases dynamically

**Comment by Aniket-Engg** [comment]
Tests run fine! Thanks @rohitsethii
